version: "3.9"

services:
  orthanc:
    image: orthanc/orthanc:latest
    container_name: ipacx-orthanc
    restart: unless-stopped
    ports:
      - "8042:8042"
      - "4242:4242"
    volumes:
      - orthanc_data:/var/lib/orthanc/db
      - ./orthanc.json:/etc/orthanc/orthanc.json:ro

volumes:
  orthanc_data:
