version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: ipacx-postgres
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ipacx_pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  ipacx_pgdata:
